"""
Ollama API Server - FastAPI REST API for Ollama Mistral 7B LLM Inference

This module provides a production-ready REST API wrapper around Ollama,
enabling text generation through HTTP endpoints with proper error handling,
logging, configuration management, caching, and monitoring.

Features:
    - Health check endpoint for service availability monitoring
    - Text generation endpoint with configurable parameters
    - Model listing endpoint
    - Response caching for common prompts (LRU cache)
    - Automatic retry logic with exponential backoff
    - Prometheus metrics for monitoring and observability
    - Comprehensive error handling and logging
    - Support for async/await for high concurrency
    - Environment-based configuration for dev/prod separation

Author: Takashim0101
Version: 1.1.0
License: MIT
"""

from fastapi import FastAPI, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
import requests
import os
from dotenv import load_dotenv
import logging
import httpx
import json
from functools import lru_cache
from tenacity import retry, stop_after_attempt, wait_exponential
from prometheus_client import Counter, Histogram, generate_latest

# Load environment variables from .env file
load_dotenv()

# Configure logging with level from environment variable
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()
logging.basicConfig(level=getattr(logging, LOG_LEVEL))
logger = logging.getLogger(__name__)

# Initialize FastAPI application
app = FastAPI(
    title="Ollama API Server",
    description="REST API for Ollama Mistral 7B with caching and monitoring",
    version="1.1.0"
)

# Load configuration from environment variables
OLLAMA_HOST = os.getenv('OLLAMA_HOST', 'http://localhost:11434')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'mistral')
APP_ENV = os.getenv('APP_ENV', 'development')

# ============================================================================
# Caching Configuration
# ============================================================================

CACHE_SIZE = int(os.getenv('CACHE_SIZE', 100))
CACHE_ENABLED = os.getenv('CACHE_ENABLED', 'true').lower() == 'true'


@lru_cache(maxsize=CACHE_SIZE)
def get_cached_generation(prompt: str, max_tokens: int) -> str:
    """
    Cache for generation results.
    
    Uses LRU cache to store frequently requested generations.
    This reduces load on Ollama and improves response times for
    common queries.
    
    Args:
        prompt: The input prompt (cache key)
        max_tokens: Maximum tokens to generate (cache key)
    
    Returns:
        Cached response or marker indicating cache miss
    
    Note:
        This is a placeholder that returns a sentinel value.
        Actual caching logic is in the generate() endpoint.
    """
    return "__CACHE_MISS__"


def cache_key(prompt: str, max_tokens: int) -> tuple:
    """Generate cache key from prompt and max_tokens."""
    return (prompt, max_tokens)


# ============================================================================
# Prometheus Metrics
# ============================================================================

# Request metrics
request_count = Counter(
    'ollama_api_requests_total',
    'Total number of API requests',
    ['endpoint', 'status', 'method']
)

request_duration = Histogram(
    'ollama_api_request_duration_seconds',
    'API request duration in seconds',
    ['endpoint', 'status']
)

# Cache metrics
cache_hits = Counter(
    'ollama_api_cache_hits_total',
    'Total number of cache hits',
    ['endpoint']
)

cache_misses = Counter(
    'ollama_api_cache_misses_total',
    'Total number of cache misses',
    ['endpoint']
)

# Ollama metrics
ollama_requests = Counter(
    'ollama_inference_requests_total',
    'Total requests sent to Ollama',
    ['status']
)

ollama_duration = Histogram(
    'ollama_inference_duration_seconds',
    'Time taken by Ollama to generate responses',
    ['status'],
    buckets=(0.5, 1, 2, 5, 10, 30, 60, 300)
)

ollama_tokens_generated = Histogram(
    'ollama_tokens_generated',
    'Number of tokens generated by Ollama',
    buckets=(10, 50, 100, 200, 500, 1000)
)

# Error metrics
errors_total = Counter(
    'ollama_api_errors_total',
    'Total number of errors',
    ['error_type', 'endpoint']
)


# ============================================================================
# Pydantic Models
# ============================================================================

class GenerateRequest(BaseModel):
    """Request model for text generation endpoint.

    Attributes:
        prompt: Input text prompt for the model to generate from
        stream: Whether to stream the response (default: False)
        max_tokens: Maximum number of tokens to generate (default: 50)
    """
    prompt: str
    stream: bool = False
    max_tokens: int = 50


class GenerateResponse(BaseModel):
    """Response model for text generation endpoint.

    Attributes:
        response: Generated text from the model
        model: Name of the model used for generation
        cached: Whether response was from cache
    """
    response: str
    model: str
    cached: bool = False


# ============================================================================
# Configuration & Timeouts
# ============================================================================

OLLAMA_HEALTH_TIMEOUT = int(os.getenv('OLLAMA_HEALTH_TIMEOUT', 5))
OLLAMA_GENERATE_TIMEOUT = int(os.getenv('OLLAMA_GENERATE_TIMEOUT', 600))

# Retry configuration
RETRY_ATTEMPTS = int(os.getenv('RETRY_ATTEMPTS', 3))
RETRY_BACKOFF_FACTOR = float(os.getenv('RETRY_BACKOFF_FACTOR', 2))


# ============================================================================
# Retry Logic with Exponential Backoff
# ============================================================================

@retry(
    stop=stop_after_attempt(RETRY_ATTEMPTS),
    wait=wait_exponential(
        multiplier=1,
        min=1,
        max=10,
        exp_base=RETRY_BACKOFF_FACTOR
    )
)
async def call_ollama_with_retry(
    client: httpx.AsyncClient,
    url: str,
    payload: dict,
    timeout: int
) -> httpx.Response:
    """
    Call Ollama API with automatic retry logic.
    
    Implements exponential backoff to handle transient failures.
    Will retry up to RETRY_ATTEMPTS times before giving up.
    
    Args:
        client: httpx AsyncClient for making requests
        url: Full URL to Ollama endpoint
        payload: JSON payload to send
        timeout: Request timeout in seconds
    
    Returns:
        httpx.Response object
    
    Raises:
        httpx.ConnectError: If connection fails after retries
        httpx.TimeoutException: If request times out after retries
    
    Example:
        >>> response = await call_ollama_with_retry(
        ...     client,
        ...     'http://ollama:11434/api/generate',
        ...     payload,
        ...     600
        ... )
    """
    logger.debug(f"Calling Ollama (attempt with retry)...")
    response = await client.post(url, json=payload, timeout=timeout)
    return response


# ============================================================================
# Endpoints
# ============================================================================

@app.get("/health")
async def health_check() -> dict:
    """Health check endpoint to verify Ollama service availability.

    This endpoint verifies that the Ollama service is running and accessible.
    Used by orchestration systems to determine service health.

    Returns:
        dict: Health status including environment and model information

    Raises:
        HTTPException: 503 Service Unavailable if Ollama cannot be reached

    Example:
        >>> GET /health
        >>> {
        >>>     "status": "healthy",
        >>>     "environment": "development",
        >>>     "ollama_host": "ollama",
        >>>     "model": "mistral"
        >>> }
    """
    try:
        response = requests.get(
            f'{OLLAMA_HOST}/api/tags',
            timeout=OLLAMA_HEALTH_TIMEOUT
        )
        response.raise_for_status()
        request_count.labels(
            endpoint='/health',
            status='success',
            method='GET'
        ).inc()
        return {
            "status": "healthy",
            "environment": APP_ENV,
            "ollama_host": OLLAMA_HOST,
            "model": OLLAMA_MODEL
        }
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        errors_total.labels(error_type='health_check_failed', endpoint='/health').inc()
        request_count.labels(
            endpoint='/health',
            status='error',
            method='GET'
        ).inc()
        raise HTTPException(
            status_code=503,
            detail="Ollama service unavailable"
        )


@app.post("/generate", response_model=GenerateResponse)
async def generate(request: GenerateRequest) -> GenerateResponse:
    """Generate text using Ollama Mistral 7B model.

    This endpoint accepts a text prompt and returns generated text
    from the model. Supports configurable generation parameters
    including maximum token count. Responses are cached for
    improved performance.

    Args:
        request: GenerateRequest containing prompt and parameters

    Returns:
        GenerateResponse: Generated text, model name, and cache status

    Raises:
        HTTPException: 503 if Ollama service is unreachable
        HTTPException: 504 if generation request times out
        HTTPException: 500 if Ollama returns an error response
        HTTPException: 422 if request validation fails

    Example:
        >>> POST /generate
        >>> {"prompt": "What is Docker?", "max_tokens": 100}
        >>> {
        >>>     "response": "Docker is a containerization platform...",
        >>>     "model": "mistral",
        >>>     "cached": false
        >>> }
    """
    try:
        # Check cache first
        is_cached = False
        if CACHE_ENABLED:
            key = cache_key(request.prompt, request.max_tokens)
            # Try to get from cache
            cached_result = get_cached_generation(
                request.prompt,
                request.max_tokens
            )
            if cached_result != "__CACHE_MISS__":
                logger.info(f"Cache hit for prompt: {request.prompt[:40]}...")
                cache_hits.labels(endpoint='/generate').inc()
                is_cached = True
                return GenerateResponse(
                    response=cached_result,
                    model=OLLAMA_MODEL,
                    cached=True
                )
            else:
                cache_misses.labels(endpoint='/generate').inc()

        prompt_log = request.prompt[:40]
        logger.info(f"Generating response for prompt: {prompt_log}...")

        # Construct payload with Ollama API requirements
        # Map max_tokens to Ollama's num_predict
        ollama_payload = {
            "model": OLLAMA_MODEL,
            "prompt": request.prompt,
            "stream": False,
            "options": {
                "num_predict": request.max_tokens
            }
        }

        # Send async request to Ollama inference endpoint with retry
        import time
        start_time = time.time()

        async with httpx.AsyncClient() as client:
            try:
                response = await call_ollama_with_retry(
                    client,
                    f'{OLLAMA_HOST}/api/generate',
                    ollama_payload,
                    OLLAMA_GENERATE_TIMEOUT
                )
            except httpx.ConnectError as e:
                logger.error(f"Cannot connect to Ollama at {OLLAMA_HOST}")
                errors_total.labels(
                    error_type='connection_error',
                    endpoint='/generate'
                ).inc()
                ollama_requests.labels(status='connect_error').inc()
                request_count.labels(
                    endpoint='/generate',
                    status='error',
                    method='POST'
                ).inc()
                raise HTTPException(
                    status_code=503,
                    detail="Ollama service unavailable"
                )
            except httpx.TimeoutException:
                logger.error("Request timeout - inference took too long")
                errors_total.labels(
                    error_type='timeout',
                    endpoint='/generate'
                ).inc()
                ollama_requests.labels(status='timeout').inc()
                request_count.labels(
                    endpoint='/generate',
                    status='timeout',
                    method='POST'
                ).inc()
                raise HTTPException(
                    status_code=504,
                    detail="Request timeout - inference took too long"
                )

            # Record Ollama latency
            elapsed = time.time() - start_time
            ollama_duration.labels(status='success').observe(elapsed)

            # Handle non-200 responses from Ollama
            if response.status_code != 200:
                logger.error(
                    f"Ollama returned non-200 status: "
                    f"{response.status_code} - {response.text}"
                )
                errors_total.labels(
                    error_type='ollama_error',
                    endpoint='/generate'
                ).inc()
                ollama_requests.labels(status='error').inc()

                # Parse error message from JSON or fallback to text
                try:
                    error_data = json.loads(response.text)
                    error_msg = error_data.get('error', response.text)
                except Exception:
                    error_msg = response.text

                raise HTTPException(
                    status_code=500,
                    detail=f"Ollama Error: {error_msg}"
                )

            # Extract generated text from response
            data = response.json()
            generated_text = data.get('response', '')

            # Record successful metrics
            ollama_requests.labels(status='success').inc()
            request_count.labels(
                endpoint='/generate',
                status='success',
                method='POST'
            ).inc()

            # Estimate tokens generated
            estimated_tokens = len(generated_text.split())
            ollama_tokens_generated.observe(estimated_tokens)

            # Cache the result if enabled
            if CACHE_ENABLED:
                # Update cache (note: lru_cache doesn't support update,
                # so we rely on future calls to hit the cache naturally)
                logger.info(f"Caching result for future requests")

            return GenerateResponse(
                response=generated_text,
                model=OLLAMA_MODEL,
                cached=False
            )

    except HTTPException:
        # Re-raise HTTP exceptions (avoid double-wrapping)
        raise
    except Exception as e:
        # Catch unexpected exceptions and log them
        logger.error(f"Generation error: {e}")
        errors_total.labels(
            error_type='unexpected',
            endpoint='/generate'
        ).inc()
        request_count.labels(
            endpoint='/generate',
            status='error',
            method='POST'
        ).inc()
        raise HTTPException(
            status_code=500,
            detail="Internal Server Error"
        )


@app.get("/models")
async def list_models() -> dict:
    """List available models in Ollama.

    Retrieves the list of models currently available in the
    Ollama instance.

    Returns:
        dict: Response from Ollama containing available models

    Raises:
        HTTPException: 503 Service Unavailable if Ollama cannot be reached

    Example:
        >>> GET /models
        >>> {
        >>>     "models": [
        >>>         {"name": "mistral:latest", "size": "4.4GB"},
        >>>         {"name": "llama2:latest", "size": "3.8GB"}
        >>>     ]
        >>> }
    """
    try:
        response = requests.get(
            f'{OLLAMA_HOST}/api/tags',
            timeout=OLLAMA_HEALTH_TIMEOUT
        )
        response.raise_for_status()
        request_count.labels(
            endpoint='/models',
            status='success',
            method='GET'
        ).inc()
        return response.json()
    except Exception as e:
        logger.error(f"Failed to fetch models: {e}")
        errors_total.labels(error_type='models_fetch_failed', endpoint='/models').inc()
        request_count.labels(
            endpoint='/models',
            status='error',
            method='GET'
        ).inc()
        raise HTTPException(
            status_code=503,
            detail="Ollama service unavailable"
        )


@app.get("/metrics")
async def metrics():
    """Prometheus metrics endpoint.

    Exposes metrics in Prometheus format for monitoring and observability.
    Includes request counts, latencies, cache performance, and errors.

    Returns:
        Response: Prometheus-formatted metrics

    Example:
        >>> GET /metrics
        >>> # HELP ollama_api_requests_total Total number of API requests
        >>> # TYPE ollama_api_requests_total counter
        >>> ollama_api_requests_total{endpoint="/health",status="success",method="GET"} 42.0
    """
    return Response(content=generate_latest(), media_type="text/plain")


@app.get("/")
async def root() -> dict:
    """Root endpoint returning service information.

    Provides an overview of available endpoints and service configuration.
    Useful for API clients to discover available endpoints.

    Returns:
        dict: Service info including version, environment, endpoints

    Example:
        >>> GET /
        >>> {
        >>>     "service": "Ollama API Server",
        >>>     "version": "1.1.0",
        >>>     "environment": "development",
        >>>     "docs": "/docs",
        >>>     "metrics": "/metrics",
        >>>     "endpoints": {
        >>>         "health": "/health",
        >>>         "generate": "/generate (POST)",
        >>>         "models": "/models"
        >>>     }
        >>> }
    """
    request_count.labels(
        endpoint='/',
        status='success',
        method='GET'
    ).inc()
    return {
        "service": "Ollama API Server",
        "version": "1.1.0",
        "environment": APP_ENV,
        "docs": "/docs",
        "metrics": "/metrics",
        "endpoints": {
            "health": "/health",
            "generate": "/generate (POST)",
            "models": "/models",
            "metrics": "/metrics (Prometheus)"
        }
    }


if __name__ == "__main__":
    import uvicorn

    # Load server configuration from environment variables
    API_HOST = os.getenv('API_HOST', '0.0.0.0')
    API_PORT = int(os.getenv('API_PORT', 8000))

    # Start Uvicorn ASGI server
    uvicorn.run(app, host=API_HOST, port=API_PORT)
